<?php

namespace metaphrase\phpsdk;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-13 at 14:42:50.
 */
class MetaphraseTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Metaphrase
     */
    protected $object;
    
    /**
     * Hardcoded settings for Metaphrase
     */
    private $settings = [
        'API_KEY' => '614a98a31bd17b3a82094ef0388b9d81',
        'language_code' => 'gr',
        'project_id' => 19
    ];
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
        $this->object = new Metaphrase($this->settings['API_KEY']);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers metaphrase\phpsdk\Metaphrase::fetch
     * @expectedException metaphrase\phpsdk\MetaphraseException
     */
    public function testFetch() {
        $translated = $this->object->fetch($this->settings['project_id'],
            $this->settings['language_code']);
        
        $this->assertNotNull($translated);
        $this->assertInternalType('array', $translated, 'Expects array');
        
        //Test negative
        $empty = $this->object->fetch(1, 
            'zn');
        
        $this->assertNull($empty);
        
    }

    /**
     * @covers metaphrase\phpsdk\Metaphrase::add_key
     * @todo   Implement testAdd_key().
     */
    public function testAdd_key() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers metaphrase\phpsdk\Metaphrase::cache_update
     * @todo   Implement testCache_update().
     */
    public function testCache_update() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers metaphrase\phpsdk\Metaphrase::cache_clear
     * @todo   Implement testCache_clear().
     */
    public function testCache_clear() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
