<?php

namespace metaphrase\phpsdk\cache;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-13 at 16:43:43.
 */
class FileTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var File
     */
    protected $object;

    protected $settings;
    
    protected $data;
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->settings = include(dirname(dirname(dirname(dirname(__DIR__)))) . '/settings.php');
        
        $this->object = new File(
            $this->settings['cache']['file']['path'], 'phparray');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers metaphrase\phpsdk\cache\File::store
     */
    public function testStore() {
        $this->assertTrue(TRUE);
        
        $data = [
            'application_title' => 'Application title'
        ];
        
        $this->object->store(
            $this->settings['project_id'], $this->settings['language_code'],
            $data
        );
        
        $this->data = $data;
    }

    /**
     * @covers metaphrase\phpsdk\cache\File::fetch
     * @depends testStore
     */
    public function testFetch() {
        $data = $this->object->fetch(
            $this->settings['project_id'], $this->settings['language_code']
        );
        
        $this->assertArrayHasKey('application_title', $data);
    }

}
